# Generated by Django 4.0.6 on 2022-07-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='modelo',
            new_name='modelo',
        ),
    ]
