# Generated by Django 4.0.6 on 2022-07-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_gato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gato',
        ),
    ]
