# Generated by Django 4.0.6 on 2022-07-18 20:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_delete_gato'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
